# Pytorch Notebook

## Basic Understanding

In [2]:
from __future__ import print_function
import sys
import torch

In [3]:
# python version and GPU check

print(sys.version)
print(torch.cuda.is_available())
print(torch.version.cuda)
print(torch.cuda.get_device_name(0))

3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)]
True
11.3
NVIDIA GeForce RTX 3070


In [4]:
# build 5x5 matrix without initiation
x = torch.empty(5,5)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [6.7683e-43, 7.7052e+31, 7.2148e+22, 1.5766e-19, 1.0256e-08],
        [6.4456e-10, 3.1645e+12, 4.3356e-08, 1.0491e-08, 2.6078e-09],
        [1.2752e+16, 2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31],
        [7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28, 7.0367e+22]])


In [5]:
# random initialized matrix
x = torch.zeros(5,5, dtype=torch.long)
print(x)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [6]:
x = torch.tensor([10, 5.5])

In [7]:
# build the tensor based on an exist tensor
x = x.new_ones(5,5, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


In [8]:
y = torch.rand(5,5)
print(y)

tensor([[0.3380, 0.7775, 0.9529, 0.1039, 0.0705],
        [0.1269, 0.9449, 0.6654, 0.9116, 0.5487],
        [0.4390, 0.6981, 0.8072, 0.6257, 0.5051],
        [0.2110, 0.2833, 0.5066, 0.8226, 0.2115],
        [0.4999, 0.3134, 0.2275, 0.3996, 0.4496]])


In [9]:
# tensor add
print(x+y)

tensor([[1.3380, 1.7775, 1.9529, 1.1039, 1.0705],
        [1.1269, 1.9449, 1.6654, 1.9116, 1.5487],
        [1.4390, 1.6981, 1.8072, 1.6257, 1.5051],
        [1.2110, 1.2833, 1.5066, 1.8226, 1.2115],
        [1.4999, 1.3134, 1.2275, 1.3996, 1.4496]], dtype=torch.float64)


In [10]:
# method 2
torch.add(x,y)

tensor([[1.3380, 1.7775, 1.9529, 1.1039, 1.0705],
        [1.1269, 1.9449, 1.6654, 1.9116, 1.5487],
        [1.4390, 1.6981, 1.8072, 1.6257, 1.5051],
        [1.2110, 1.2833, 1.5066, 1.8226, 1.2115],
        [1.4999, 1.3134, 1.2275, 1.3996, 1.4496]], dtype=torch.float64)

In [11]:
result = torch.empty(5,5)
torch.add(x,y, out=result)
print(result)

tensor([[1.3380, 1.7775, 1.9529, 1.1039, 1.0705],
        [1.1269, 1.9449, 1.6654, 1.9116, 1.5487],
        [1.4390, 1.6981, 1.8072, 1.6257, 1.5051],
        [1.2110, 1.2833, 1.5066, 1.8226, 1.2115],
        [1.4999, 1.3134, 1.2275, 1.3996, 1.4496]])


In [12]:
y.add_(x)

tensor([[1.3380, 1.7775, 1.9529, 1.1039, 1.0705],
        [1.1269, 1.9449, 1.6654, 1.9116, 1.5487],
        [1.4390, 1.6981, 1.8072, 1.6257, 1.5051],
        [1.2110, 1.2833, 1.5066, 1.8226, 1.2115],
        [1.4999, 1.3134, 1.2275, 1.3996, 1.4496]])

In [13]:
# indexing as numpy
print(y[:,1])

tensor([1.7775, 1.9449, 1.6981, 1.2833, 1.3134])


In [14]:
# torch.autograd is Pytorch's automatic differentiation engine powering neural network training

x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [15]:
y = x +2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [17]:
z = y*y*3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [18]:
a = torch.randn(2,2)
a = ((a*3) / (a -1))
print(a.requires_grad)

False


In [20]:
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

True
tensor(4612.3477, grad_fn=<SumBackward0>)


In [25]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [27]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
