# Pytorch Notebook

## Basic Understanding

In [1]:
from __future__ import print_function
import sys
import torch

In [8]:
# python version and GPU check

print(sys.version)
print(torch.cuda.is_available())
print(torch.version.cuda)
print(torch.cuda.get_device_name(0))

3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)]
True
11.3
NVIDIA GeForce RTX 3070


In [10]:
# build 5x5 matrix without initiation
x = torch.empty(5,5)
print(x)

tensor([[0.0000e+00, 5.8434e-43, 7.7052e+31, 7.2148e+22, 1.5766e-19],
        [1.0256e-08, 6.4456e-10, 3.1473e+12, 2.7096e-09, 4.3208e-05],
        [6.6757e-07, 1.2681e+16, 2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
        [7.0367e+22, 2.1715e-18, 2.1572e-04, 1.0267e-08, 5.2004e+22]])


In [22]:
# random initialized matrix
x = torch.zeros(5,5, dtype=torch.long)
print(x)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [23]:
x = torch.tensor([10, 5.5])

In [24]:
# build the tensor based on an exist tensor
x = x.new_ones(5,5, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


In [25]:
y = torch.rand(5,5)
print(y)

tensor([[0.8145, 0.3139, 0.3493, 0.8403, 0.6630],
        [0.9124, 0.3118, 0.2353, 0.1771, 0.7505],
        [0.0289, 0.1948, 0.0110, 0.9484, 0.0377],
        [0.8052, 0.2618, 0.9360, 0.7093, 0.8846],
        [0.5737, 0.2802, 0.1402, 0.7590, 0.9565]])


In [26]:
# tensor add
print(x+y)

tensor([[1.8145, 1.3139, 1.3493, 1.8403, 1.6630],
        [1.9124, 1.3118, 1.2353, 1.1771, 1.7505],
        [1.0289, 1.1948, 1.0110, 1.9484, 1.0377],
        [1.8052, 1.2618, 1.9360, 1.7093, 1.8846],
        [1.5737, 1.2802, 1.1402, 1.7590, 1.9565]], dtype=torch.float64)


In [28]:
# method 2
torch.add(x,y)

tensor([[1.8145, 1.3139, 1.3493, 1.8403, 1.6630],
        [1.9124, 1.3118, 1.2353, 1.1771, 1.7505],
        [1.0289, 1.1948, 1.0110, 1.9484, 1.0377],
        [1.8052, 1.2618, 1.9360, 1.7093, 1.8846],
        [1.5737, 1.2802, 1.1402, 1.7590, 1.9565]], dtype=torch.float64)

In [29]:
result = torch.empty(5,5)
torch.add(x,y, out=result)
print(result)

tensor([[1.8145, 1.3139, 1.3493, 1.8403, 1.6630],
        [1.9124, 1.3118, 1.2353, 1.1771, 1.7505],
        [1.0289, 1.1948, 1.0110, 1.9484, 1.0377],
        [1.8052, 1.2618, 1.9360, 1.7093, 1.8846],
        [1.5737, 1.2802, 1.1402, 1.7590, 1.9565]])


In [30]:
y.add_(x)

tensor([[1.8145, 1.3139, 1.3493, 1.8403, 1.6630],
        [1.9124, 1.3118, 1.2353, 1.1771, 1.7505],
        [1.0289, 1.1948, 1.0110, 1.9484, 1.0377],
        [1.8052, 1.2618, 1.9360, 1.7093, 1.8846],
        [1.5737, 1.2802, 1.1402, 1.7590, 1.9565]])

In [31]:
# indexing as numpy
print(y[:,1])

tensor([1.3139, 1.3118, 1.1948, 1.2618, 1.2802])


In [ ]:
# torch.autograd is Pytorch's automatic differentiation engine powering neural network training